language: java
jdk:
  - oraclejdk8
  
install: echo "I trust Maven."

# don't just run the tests, also run Findbugs and friends
script: mvn verify

notifications:
  email:
    recipients:
      - angelo.zerr@gmail.com